spring:
  datasource:
    password: letmein
    url: jdbc:mysql:/localhost:3306/serverdb
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialiect: org.hiebrnate.dialiect.MySQL8Dialect
        format_sql: true
    show-sql: true